
# Test GET /posts
# description: Get all posts

GET http://localhost:4000/posts


# Test POST /posts
# description: Create a new post

POST http://localhost:4000/posts
Content-Type: application/json

{
  "title": "Titulo de ejemplo"
}


# Test GET /posts/:id/comments
# description: Get all comments associated to a post

GET http://localhost:4001/posts/1/comments


# Test POST /posts/:id/comments
# description: Create a new comment associated to a post

POST http://localhost:4001/posts/1/comments
Content-Type: application/json

{
  "content": "Comentario de ejemplo"
}


# Test GET /posts
# description: Get all posts with comments
GET http://localhost:4002/posts